# -*- coding: utf-8 -*-
"""Data_Smartphone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rp0zWQMzdzKbj_MqT1cjtNdXAI0-n8Cj

**Langkah - langkah mendapatkan data brand HP di dunia via wikipedia.org**
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://en.wikipedia.org/wiki/List_of_mobile_phone_brands_by_country'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

tables = soup.find_all('table', {'class': 'wikitable'})

data = []
for table in tables:
    rows = table.find_all('tr')[1:]  # Skip header row
    current_country = ''  # Untuk menyimpan negara saat ini

    for row in rows:
        cols = row.find_all('td')
        col_texts = [col.text.strip() for col in cols]

        if len(col_texts) == 3:
            # Format Lengkap : Country, Brand, Notes
            current_country = col_texts[0]
            brand = col_texts[1]
            notes = col_texts[2]
        elif len(col_texts) == 2:
            # Format : Brand, Notes (Country mengikuti sebelumnya)
            brand = col_texts[0]
            notes = col_texts[1]
        elif len(col_texts) == 1:
            # Format : Country (Brand dan Notes mengikuti sebelumnya)
            brand = col_texts[0]
            notes = ''
        else:
            continue # skip baris kosong atau tidak dikenal

        data.append({
            'Country': current_country,
            'Brand': brand,
            'Notes': notes
        })

df = pd.DataFrame(data)
df.to_csv('Data_Smartphone.csv', index=False)

print(df)
df.info()

df.dropna(inplace=True)
print(df.head())

df.drop(columns=['Notes'], inplace=True)
print(df.head())

df.to_csv('Data_Smartphone.csv', index=False)

import matplotlib.pyplot as plt

df = pd.read_csv('Data_Smartphone.csv')

brand_count = df['Country'].value_counts().head(15)  # Ambil 15 negara teratas

# Buat diagram batang
plt.figure(figsize=(12, 6))
brand_count.plot(kind='bar', color='skyblue')

# Tambahkan judul dan label
plt.title('Jumlah Merek Smartphone per Negara (Top 15)', fontsize=14)
plt.xlabel('Negara', fontsize=12)
plt.ylabel('Jumlah Merek', fontsize=12)
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Tampilkan grafik
plt.tight_layout()
plt.show()

